version: '3.4'

services:
  productapi:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: ProductApi/Dockerfile

  orderapi:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: OrderApi/Dockerfile

# Uncomment the following code, if you want to run RabbitMQ server
# as a container:
#  rabbitmq:
#    image: rabbitmq:3-management
#    ports:
#    - "15673:15672"